# Generated by Django 5.1.2 on 2024-11-02 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='accepted_users',
            field=models.ManyToManyField(blank=True, related_name='accepted_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
