# Generated by Django 5.1.5 on 2025-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_portfoliolink_profile_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_conversation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
