# Generated by Django 5.1.2 on 2024-11-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experience_accepted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_team_project',
            field=models.BooleanField(default=False, help_text='Check if this is a team project.'),
        ),
    ]
