# Generated by Django 5.1 on 2024-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_experience_is_team_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_project_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=300),
        ),
    ]
