# Generated by Django 5.1.5 on 2025-02-22 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_image_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_project_card_id', models.IntegerField(blank=True, null=True)),
                ('related_post_id', models.IntegerField(blank=True, null=True)),
                ('related_comment_id', models.IntegerField(blank=True, null=True)),
                ('related_user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
