# Generated by Django 5.1.5 on 2025-02-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reporttest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportTest',
            new_name='Report',
        ),
    ]
