# Generated by Django 5.1 on 2024-11-14 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_notification_related_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
