# Generated by Django 5.1.5 on 2025-02-22 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_reporttest_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCardInvitationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_project_card_invitation_links', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_project_card_invitation_links', to=settings.AUTH_USER_MODEL)),
                ('project_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='api.projectcard')),
            ],
            options={
                'unique_together': {('inviter', 'link')},
            },
        ),
    ]
