# Generated by Django 5.1 on 2024-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_project_liked_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation_register", "Invitation Register"),
                    ("invitation_expired", "Invitation Expired"),
                    ("friend_accept", "Friend Accept"),
                    ("friend_reject", "Friend Reject"),
                    ("friend_request", "Friend Request"),
                    ("project_tag", "Project Tag"),
                    ("new_comment", "New Comment"),
                    ("reply_comment", "Reply Comment"),
                    ("project_profile_keyword", "Project Profile Keyword"),
                    ("experience_request", "Experience Request"),
                ],
                max_length=30,
            ),
        ),
    ]
