# Generated by Django 5.1 on 2024-11-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="profiles",
        ),
        migrations.AddField(
            model_name="experience",
            name="creator_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation_register", "Invitation Register"),
                    ("invitation_expired", "Invitation Expired"),
                    ("friend_accept", "Friend Accept"),
                    ("friend_reject", "Friend Reject"),
                    ("friend_request", "Friend Request"),
                    ("project_tag", "Project Tag"),
                    ("new_comment", "New Comment"),
                    ("reply_comment", "Reply Comment"),
                    ("project_profile_keyword", "Project Profile Keyword"),
                    ("experience_request", "Experience Request"),
                    ("experience_accept", "Experience Accept"),
                    ("experience_reject", "Experience Reject"),
                ],
                max_length=30,
            ),
        ),
    ]
