# Generated by Django 5.1.2 on 2024-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_experience_profiles_experience_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedetail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencedetail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
