# Generated by Django 5.1.2 on 2024-11-20 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_experience_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='collaborators',
        ),
        migrations.CreateModel(
            name='ExperienceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='pending_users',
            field=models.ManyToManyField(blank=True, related_name='pending_invitations', to='api.experienceinvitation'),
        ),
    ]
