# Generated by Django 5.1.2 on 2024-11-21 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_experience_collaborators_experienceinvitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='pending_users',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tags',
        ),
        migrations.AddField(
            model_name='experiencedetail',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='api.keyword'),
        ),
        migrations.AddField(
            model_name='experienceinvitation',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations', to='api.experience'),
        ),
        migrations.AlterField(
            model_name='experienceinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experienceinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
