# Generated by Django 5.1 on 2024-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="deleted_for_user1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="deleted_for_user2",
            field=models.BooleanField(default=False),
        ),
    ]
