# Generated by Django 5.1 on 2024-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
