# Generated by Django 5.1 on 2024-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="message_images/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
