# Generated by Django 5.1 on 2024-12-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_message_image_alter_message_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
