# Generated by Django 5.1 on 2024-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_message_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation_register", "Invitation Register"),
                    ("invitation_expired", "Invitation Expired"),
                    ("friend_accept", "Friend Accept"),
                    ("friend_reject", "Friend Reject"),
                    ("friend_request", "Friend Request"),
                    ("project_tag", "Project Tag"),
                    ("new_comment", "New Comment"),
                    ("reply_comment", "Reply Comment"),
                    ("project_profile_keyword", "Project Profile Keyword"),
                    ("experience_register", "Experience Register"),
                    ("experience_request", "Experience Request"),
                    ("experience_accept", "Experience Accept"),
                    ("experience_reject", "Experience Reject"),
                    ("experience_deleted", "Experience Deleted"),
                    ("experience_invitation_deleted", "Experience Invitation Deleted"),
                    ("new_message", "New Message"),
                ],
                max_length=30,
            ),
        ),
    ]
