# Generated by Django 5.1.5 on 2025-01-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_project_project_card_alter_project_user_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post'),
        ),
    ]
