# Generated by Django 5.1.5 on 2025-01-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_comment_project_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='portfolioLink',
            new_name='portfolio_link',
        ),
    ]
