# Generated by Django 5.1.5 on 2025-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_portfoliolink_portfoliolink_portfolio_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_project_id',
            new_name='related_post_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_project_card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation_register', 'Invitation Register'), ('invitation_expired', 'Invitation Expired'), ('friend_accept', 'Friend Accept'), ('friend_reject', 'Friend Reject'), ('friend_request', 'Friend Request'), ('project_card_invite', 'ProjectCard Invite'), ('project_card_accept', 'ProjectCard Accept'), ('project_card_reject', 'ProjectCard Reject'), ('project_card_update', 'ProjectCard Update'), ('project_card_recommend', 'ProjectCard Recommend'), ('post_create_team', 'Post Create Team'), ('post_update_team', 'Post Update Team'), ('post_create_save', 'Post Create Save'), ('post_update_save', 'Post Update Save'), ('post_like', 'Post Like'), ('comment_create', 'Comment Create'), ('comment_child_create', 'Comment Child Create'), ('comment_update', 'Comment Update'), ('comment_child_update', 'Comment Child Update'), ('new_message', 'New Message')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
